//<M>
//×-
//@-FILENÉV   : JS_CHARTS_FROM_SCRATCH - consts.js-@
//@-SZERZŐ    : AX07057-@
//@-LÉTREHOZVA: 2018. ápr. 19.-@
//@-FÜGGŐSÉGEK:
//×-
// @-- RQRD_FILE01.js-@
// @-- RQRD_FILE02.js-@
// @-- RQRD_FILE03.js-@
// @-- RQRD_FILE04.js-@
//-@
//-×
//-@
//@-LEÍRÁS    :
// Ez a file tartalmazza a programfutás során a javascript számára szükséges konstansokat.
//@-MÓDOSÍTÁSOK :
//×-
// @-- ... -@
//-×
//-×
//</M>

var PSTCG = PSTCG || {};

var PSTCG_CNSTS = PSTCG_CNSTS || {}; 

//<nn>
// Az alapértelmezett = DEF[AULT] értékeket tartalmazó objektum.
//</nn>
PSTCG_CNSTS.DEFS = {};

//<nn>
// Az 
//×-
// @-- alapértelemzett = BASE -@
// @-- kicsi = S -@
// @-- SVG elem = SVG -@
//@-- elemei = W/H/MRG_T/B/L/R, ... -@
//-×
//</nn>
PSTCG_CNSTS.DEFS.BASE_S_SVG_W = 200;
PSTCG_CNSTS.DEFS.BASE_S_SVG_H = 200;
PSTCG_CNSTS.DEFS.BASE_S_SVG_MRG_T = 20;
PSTCG_CNSTS.DEFS.BASE_S_SVG_MRG_B = 10;
PSTCG_CNSTS.DEFS.BASE_S_SVG_MRG_L = 10;
PSTCG_CNSTS.DEFS.BASE_S_SVG_MRG_R = 10;
PSTCG_CNSTS.DEFS.BASE_S_SVG_BGRECT_DIMS = [180,170];

//<nn>
// Az alapszínek...
//</nn>
PSTCG_CNSTS.DEFS.COLORS = {};
PSTCG_CNSTS.DEFS.COLORS.BLACK = "#000000";
PSTCG_CNSTS.DEFS.COLORS.GRAY01 = "#252525";
PSTCG_CNSTS.DEFS.COLORS.GRAY02 = "#454545";
PSTCG_CNSTS.DEFS.COLORS.GRAY03 = "#656565";
PSTCG_CNSTS.DEFS.COLORS.GRAY04 = "#858585";
PSTCG_CNSTS.DEFS.COLORS.GRAY05 = "#A5A5A5";
PSTCG_CNSTS.DEFS.COLORS.GRAY06 = "#C5C5C5";
PSTCG_CNSTS.DEFS.COLORS.GRAY07 = "#E5E5E5";
PSTCG_CNSTS.DEFS.COLORS.WHITE = "#FFFFFF";
PSTCG_CNSTS.DEFS.COLORS.RED = "#FF0000";
PSTCG_CNSTS.DEFS.COLORS.GREEN = "#00FF00";
PSTCG_CNSTS.DEFS.COLORS.BLUE = "#0000FF";
PSTCG_CNSTS.DEFS.COLORS.YELLOW = "#FFFF00";
PSTCG_CNSTS.DEFS.COLORS.TURQUISE = "#00FFFF";
PSTCG_CNSTS.DEFS.COLORS.MAGENTA = "#FF00FF";

PSTCG_CNSTS.SVGNS = "http://www.w3.org/2000/svg";











